### ISSUE TITLE
play again

### ISSUE THREAD

**Issue by samridhi18** [ishandeveloper/Tic-Tac-Toe#2]
it doesnot show play again when the game goes draw

**Comment by ishandeveloper** [comment]
Hi @samridhi18, 
Whoops, looks like I forgot an edge case 🤦🏻‍♂️.
Thank you so much for taking the time and reporting this issue. I'll surely fix it today.

**Comment by samridhi18** [comment]
yeah sure!!

**Comment by ishandeveloper** [comment]
Fixed it in commit #[ef6bf97](https://github.com/ishandeveloper/Tic-Tac-Toe/commit/ef6bf9701f7eb7ab83a28fd22339523e8905d535)
