### ISSUE TITLE
No Display Message/Redirection When Nobody Wins

### ISSUE THREAD

**Issue by KushalBhanot** [ishandeveloper/Tic-Tac-Toe#5]
### To recreate this issue: 

1. Start playing from both O and X's sides and make sure nobody wins.
2. You'll see that there's no option to go back to the initial stage and nothing is displayed on the user's screen.

<img width="1000px" alt="Screenshot" src="https://user-images.githubusercontent.com/51001134/93047466-342c8f80-f67a-11ea-8d43-d11edc38421a.png">

**Comment by KushalBhanot** [comment]
The issue occurs only in the live version and not on local machine run.

**Comment by ishandeveloper** [comment]
### Hey @KushalBhanot ! Thanks for taking out the time to discover the bug and open this issue.

It looks like, I forgot to deploy the changes to vercel after [#ef6bf97](https://github.com/ishandeveloper/Tic-Tac-Toe/commit/ef6bf9701f7eb7ab83a28fd22339523e8905d535) commit. I've redeployed the app, and this should fix the issue.

![screely-1600069115196](https://user-images.githubusercontent.com/54989142/93057376-6a263f80-f68b-11ea-8766-20a406dc289d.png)

Please test this out, and let me know if any issue still persists. If everything's working as expected on your end, then please move forward and close this issue.

Thank you for your contribution! ✨

**Comment by KushalBhanot** [comment]
**Yup, that's it.** I was thinking of resolving the issue myself and making a PR. But since the issue was deployment-related, I let it go.

Cheers ⚡️
